### ISSUE TITLE
본문 내용의 개선

### ISSUE THREAD

**Issue by redgoose-dev** [redgoose-dev/goose-manager#93]
> 참고링크: https://note.redgoose.me/article/1767/#유연하게_필드_사이즈_변경해주는_속성

새로운 css 속성이 나왔는데 아직 테스트는 안해봤지만 설명만 봐도 정말 필요해왔던 기능이었다.
input, textarea 엘리먼트에서 적용 시도를 꼭 해보고 싶다.

```css
input { field-sizing: content; }
```

이 기능은 유연한 입력폼 사이즈에 대한 기능을 가지고 있다. 마치 `<div contenteditable="true"/>`와 같은 모습을 구현할 수 있다는 것이다. 흠..
